### ISSUE TITLE
issue with make_gtfs.main.build_trips(pfeed, routes, service_by_window)

### ISSUE THREAD

**Issue by JanineCHEN** [mrcagney/make_gtfs#2]
I tried to conduct the following code following the example.ipynb provided in the repository:
`routes = mg.build_routes(pfeed)`
`trips = mg.build_trips(pfeed,routes,f.service_window_id)`
Then get the following error:
`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-21-f3e87d2c0dd1> in <module>
         1 routes = mg.build_routes(pfeed)
----> 2 trips = mg.build_trips(pfeed,routes,f.service_window_id)

~\Desktop\GTFS\make_gtfs\make_gtfs\main.py in build_trips(pfeed, routes, service_by_window)
    203         # (bad input)
    204         num_trips_per_direction = int(frequency*duration)
--> 205         service = service_by_window[window]
    206         direction = row['direction']
    207         if direction == 2:

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py in __getitem__(self, key)
    866         key = com.apply_if_callable(key, self)
    867         try:
--> 868             result = self.index.get_value(self, key)
    869 
    870             if not is_scalar(result):

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_value(self, series, key)
   4373         try:
   4374             return self._engine.get_value(s, k,
-> 4375                                           tz=getattr(series.dtype, 'tz', None))
   4376         except KeyError as e1:
   4377             if len(self) > 0 and (self.holds_integer() or self.is_boolean()):

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index_class_helper.pxi in pandas._libs.index.Int64Engine._check_type()

KeyError: 'weekday_peak_1'`

Seems like it's getting trouble with the service_by_window(dictionary). It would be great if anyone can shed some light on this issue!

**Comment by araichev** [comment]
@JanineCHEN can you provide the code and data for a minimal example that triggers this error? I can't debug your example as is, because i don't know what ``pfeed`` is  or what ``f`` is.

**Comment by JanineCHEN** [comment]
> @JanineCHEN can you provide the code and data for a minimal example that triggers this error? I can't debug your example as is, because I don't know what `pfeed` is or what `f` is.

Thank you for getting back to me, pls refer to the following code (I'm using the auckland data provided by the repository, with same file structure):
```
import sys
from pathlib import Path

import pandas as pd
import numpy as np
import gtfstk as gt

sys.path.append('../')

import make_gtfs as mg

DATA_DIR = Path('../data')
%load_ext autoreload
%autoreload 2
path = DATA_DIR/'auckland'
pfeed = mg.read_protofeed(path)
feed = mg.build_feed(pfeed)

f = pd.merge(feed.routes[['route_id', 'route_short_name']], pfeed.frequencies)
f = pd.merge(f, pfeed.service_windows).sort_values('route_id')

routes = mg.build_routes(pfeed)
trips = mg.build_trips(pfeed,routes,f.service_window_id)
```
And it gives me the following error message:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-8-867debc1fe7a> in <module>
----> 1 trips = mg.build_trips(pfeed,routes,f.service_window_id)
      2 trips
      3 # mg.build_trips

~\Desktop\GTFS\make_gtfs\make_gtfs\main.py in build_trips(pfeed, routes, service_by_window)
    203         # (bad input)
    204         num_trips_per_direction = int(frequency*duration)
--> 205         service = service_by_window[window]
    206         direction = row['direction']
    207         if direction == 2:

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py in __getitem__(self, key)
    866         key = com.apply_if_callable(key, self)
    867         try:
--> 868             result = self.index.get_value(self, key)
    869 
    870             if not is_scalar(result):

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_value(self, series, key)
   4373         try:
   4374             return self._engine.get_value(s, k,
-> 4375                                           tz=getattr(series.dtype, 'tz', None))
   4376         except KeyError as e1:
   4377             if len(self) > 0 and (self.holds_integer() or self.is_boolean()):

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index_class_helper.pxi in pandas._libs.index.Int64Engine._check_type()

KeyError: 'weekday_peak_1'
```

Any insight on why this happens? Thank you!

**Comment by araichev** [comment]
@JanineCHEN the last input of the function ``build_trips`` needs to be a service-by-window dictionary. Your code passes in a Pandas Series

**Comment by JanineCHEN** [comment]
> @JanineCHEN the last input of the function `build_trips` needs to be a service-by-window dictionary. Your code passes in the Pandas Series `f.service_window_id`.

Sorry, when you say service-by-window dictionary, do you mean a transfer of the original service_windows.csv file into a dictionary from the data folder, or some other dictionary created by previous steps which I have overlooked? It would be super if you could give me a sample code for what you mean. Forgive me, I'm kind of newbie for this.
