### ISSUE TITLE
Can't start make_gtfs

### ISSUE THREAD

**Issue by viajerus** [mrcagney/make_gtfs#2]
Hello, 

I've followed the instructions to run make_gtfs using poetry and this is the error that I get when I run "poetry add make_gtfs".
<img width="489" alt="Bildschirmfoto 2024-07-05 um 19 14 49" src="https://github.com/mrcagney/make_gtfs/assets/63015973/6536cfa6-dd4c-412f-8b52-29a63d369776">

**Comment by araichev** [comment]
Hi @viajerus if you're installing `make_gtfs` as a library in a separate project, then you need to name your project something other than `make_gtfs`. 
If you're cloning `make_gtfs` and doing calculations therein, then you need to run `poetry install`.

**Comment by viajerus** [comment]
Thanks!
But now I face another issue: the package geo-kit. 

![image](https://github.com/mrcagney/make_gtfs/assets/63015973/7d748ed6-7a7a-4b16-9ccd-765b4a278b87)

I also can't find further image regarding the geo-kit package.

**Comment by araichev** [comment]
Ah, yes, Geo Kit` is no longer public.
OK, i'll look into vendorizing its dependency into Make GTFS this week.

**Comment by araichev** [comment]
OK, i removed that private dependency and cleaned up some. New release for you to try.
