### ISSUE TITLE
Help running make_gtfs from command line

### ISSUE THREAD

**Issue by ptzenos** [mrcagney/make_gtfs#3]
Hi, I'm trying to run make_gtfs from the command line as a standalone application. 

Tried to install it multiple times by using both alternatives (create a new project and run "poetry add make_gtfs" / git clone and run "poetry install --no-root && pre-commit install"). 

Everything seem to complete successfully no matter the method I use, but when I type make_gtfs --help all I get is "make_gtfs: command not found".

As I haven't used poetry before and my python skills are very very limited, I'm almost sure that I'm missing something obvious here but I'm not sure where to start. 

Thanks

**Comment by araichev** [comment]
Ah, it appears the library wasn't registering the CLI properly. Try it now with the new release 4.1.0, which has instructions for UV, which is easier to use than Poetry.

**Comment by ptzenos** [comment]
Ok, I've installed UV, ran "uv add make_gtfs". I then went to the .venv/bin directory and ran ./make_gtfs --help. It was complaining about an unresolved dependency which was resolved after running "uv add click". 

Now the command returns the usage instructions, so I suppose it works. I'll now try to generate some gtfs feeds.

Thanks again for your help!

**Comment by araichev** [comment]
You're welcome @ptzenos , and thanks for describing your usage. 
I've now added the Click dependency ---don't know how i forgot it in the first place--- and clarified the UV usage instructions.
(Just do `uv run make_gtfs --help` without changing directories.)
New version 4.1.1 released now.
