### ISSUE TITLE
service_by_window dictionary in build_trips(pfeed, routes, service_by_window) function

### ISSUE THREAD

**Issue by JanineCHEN** [mrcagney/make_gtfs#3]
Please correct me if I am mistaken, by service_by_window dictionary in the `build_trips(pfeed, routes, service_by_window) ` function, does it suppose to mean the following (I'm using the provided data in the repository with the same file structure):
```
import sys
from pathlib import Path
import pandas as pd
import numpy as np
import gtfstk as gt

sys.path.append('../')

import make_gtfs as mg

DATA_DIR = Path('../data')
path = DATA_DIR/'auckland'

service_by_window = pd.read_csv(DATA_DIR/'auckland/service_windows.csv')
service_by_window = service_by_window.set_index('service_window_id').T.to_dict('list')
service_by_window
```
The outputs:
```
{'weekday_peak_1': ['07:00:00', '09:00:00', 1, 1, 1, 1, 1, 0, 0],
 'weekday_peak_2': ['15:00:00', '17:00:00', 1, 1, 1, 1, 1, 0, 0],
 'weekday_offpeak': ['09:00:00', '15:00:00', 1, 1, 1, 1, 1, 0, 0],
 'saturday': ['09:00:00', '19:00:00', 0, 0, 0, 0, 0, 1, 0]}
```
Then when I run the build_trips function:
```
pfeed = mg.read_protofeed(path)
routes = mg.build_routes(pfeed)
trips = mg.build_trips(pfeed,routes,service_by_window)
trips
```
It gives me this, in which the service_id does not seems to make too much sense for me:
![image](https://user-images.githubusercontent.com/37527041/66545842-2f0fb800-eb6e-11e9-8254-4ff63a9faecb.png)

If the dictionary supposes to have different keys and corresponding values, can you kindly enlight me? thank you!

**Comment by araichev** [comment]
@JanineCHEN see line https://github.com/mrcagney/make_gtfs/blob/master/make_gtfs/main.py#L86 for an example dictionary.
It has the form <service window ID> -> <service ID>.

Stepping back, do you need to separately build trips in your application?
Will building the entire feed via the function ``build_feed()`` be sufficient?

**Comment by JanineCHEN** [comment]
> @JanineCHEN see line https://github.com/mrcagney/make_gtfs/blob/master/make_gtfs/main.py#L86 for an example dictionary.
> It has the form -> .
> 
> Stepping back, do you need to separately build trips in your application?
> Will building the entire feed via the function `build_feed()` be sufficient?

@araichev Thanks, araichev, for your insight. I think I have found the solution to my question already. So finally what I did is the following:
```
calendar = mg.build_calendar_etc(pfeed)
calendar[1]
```
The dictionary:
```
{'weekday_peak_1': 'srv1111100',
 'weekday_peak_2': 'srv1111100',
 'weekday_offpeak_1': 'srv1111100',
 'weekday_offpeak_2': 'srv1111100',
 'weekday_offpeak_3': 'srv1111100',
 'weekend': 'srv0000011'}
```
Then I directly called `calendar[1]` in the `build_trips` function:
`trips = mg.build_trips(pfeed, feed.routes, calendar[1])`

And you are absolutely right, I can simply build the entire feed via the function build_feed(), instead of building them separately.
